# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

let
  fromEnv = import (modulesPath + "/../lib/from-env.nix");
  nixosConfigDir = builtins.dirOf nixosConfigPath;
  nixosConfigPath = fromEnv "NIXOS_CONFIG" <nixos-config>;
in
{
  config = {
    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "ehci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
      "sr_mod"
    ];
    boot.initrd.kernelModules = [
    ];
    boot.kernelModules = [
    ];
    boot.extraModulePackages = [
    ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    # Enables non-free firmware on devices not recognized by `nixos-generate-config`.
    hardware.enableRedistributableFirmware = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

    system.extraSystemBuilderCmds = lib.mkIf config.system.copySystemConfiguration ''
      ln -s ${lib.escapeShellArg (nixosConfigDir + "/hardware-configuration.nix")} "$out/hardware-configuration.nix"'';
  };
}
# vim: set sta et sw=2 ts=8:
