[revset-aliases]
'builtin_log()' = 'present(@) | ancestors(immutable_heads().., 2) | present(trunk())'
'builtin_remote_trunk_bookmarks(remote_pattern)' = '''
remote_bookmarks(exact:"main", remote_pattern) |
remote_bookmarks(exact:"master", remote_pattern) |
remote_bookmarks(exact:"trunk", remote_pattern)
'''
'remote_trunk_bookmarks(remote_pattern)' = 'builtin_remote_trunk_bookmarks(remote_pattern)'
'builtin_upstream_trunks()' = 'remote_trunk_bookmarks(exact:"upstream")'
'upstream_trunks()' = 'builtin_upstream_trunks()'
'builtin_upstream_trunks(remote_pattern)' = 'upstream_trunks() & remote_trunk_bookmarks(remote_pattern)'
'upstream_trunks(remote_pattern)' = 'builtin_upstream_trunks(remote_pattern)'
'builtin_midstream_trunks()' = 'remote_trunk_bookmarks(exact:"origin")'
'midstream_trunks()' = 'builtin_midstream_trunks()'
'builtin_midstream_trunks(remote_pattern)' = 'midstream_trunks() & remote_trunk_bookmarks(remote_pattern)'
'midstream_trunks(remote_pattern)' = 'builtin_midstream_trunks(remote_pattern)'
'builtin_remote_trunks()' = 'upstream_trunks() | midstream_trunks()'
'remote_trunks()' = 'builtin_remote_trunks()'
'builtin_remote_trunks(remote_pattern)' = 'remote_trunks() & remote_trunk_bookmarks(remote_pattern)'
'remote_trunks(remote_pattern)' = 'builtin_remote_trunks(remote_pattern)'
'builtin_downstream_trunks()' = 'remote_trunks() ~ (upstream_trunks() | midstream_trunks())'
'downstream_trunks()' = 'builtin_downstream_trunks()'
'builtin_downstream_trunks(remote_pattern)' = 'downstream_trunks() & remote_trunks(remote_pattern)'
'downstream_trunks(remote_pattern)' = 'builtin_downstream_trunks(remote_pattern)'
'builtin_upstream_trunk(remote_pattern)' = 'latest(upstream_trunks(remote_pattern))'
'upstream_trunk(remote_pattern)' = 'builtin_upstream_trunk(remote_pattern)'
'builtin_upstream_trunk()' = 'latest(upstream_trunks())'
'upstream_trunk()' = 'builtin_upstream_trunk()'
'builtin_midstream_trunk(remote_pattern)' = 'latest(midstream_trunks(remote_pattern))'
'midstream_trunk(remote_pattern)' = 'builtin_midstream_trunk(remote_pattern)'
'builtin_midstream_trunk()' = 'latest(midstream_trunks())'
'midstream_trunk()' = 'builtin_midstream_trunk()'
'builtin_downstream_trunk(remote_pattern)' = 'latest(downstream_trunks(remote_pattern))'
'downstream_trunk(remote_pattern)' = 'builtin_downstream_trunk(remote_pattern)'
'builtin_downstream_trunk()' = 'latest(downstream_trunks())'
'downstream_trunk()' = 'builtin_downstream_trunk()'
'builtin_remote_trunk(remote_pattern)' = 'latest(coalesce(upstream_trunk(remote_pattern) | midstream_trunk(remote_pattern), downstream_trunk(remote_pattern)))'
'remote_trunk(remote_pattern)' = 'builtin_remote_trunk(remote_pattern)'
'builtin_remote_trunk()' = 'latest(coalesce(upstream_trunk() | midstream_trunk(), downstream_trunk()))'
'remote_trunk()' = 'builtin_remote_trunk()'
'builtin_trunks()' = 'remote_trunks()'
'trunks()' = 'builtin_trunks()'
'builtin_trunk()' = 'coalesce(remote_trunk(), root())'
'trunk()' = 'builtin_trunk()'
