[git]
private-commits = 'private()'

[revset-aliases]
'remote_plural_immutable_trunk_bookmarks(remote_pattern)' = '''
builtin_remote_plural_immutable_trunk_bookmarks(remote_pattern) |
remote_bookmarks(glob:"integration/**/*", remote_pattern)
'''
'remote_plural_mutable_trunk_bookmarks(remote_pattern)' = '''
builtin_remote_plural_mutable_trunk_bookmarks(remote_pattern)
'''

'recent_committer_date()' = 'none()'
'log_domain()' = 'builtin_log_domain() | heads(recent_committer_date())'

'private()' = 'description(glob:"[[]PRIVATE[]]*")'
