[revset-aliases]
'builtin_remote_trunk_bookmarks(remote_pattern)' = '''
remote_bookmarks(exact:"main", remote_pattern) |
remote_bookmarks(exact:"master", remote_pattern) |
remote_bookmarks(exact:"trunk", remote_pattern)
'''
'remote_trunk_bookmarks(remote_pattern)' = 'builtin_remote_trunk_bookmarks(remote_pattern)'
'builtin_remote_trunk_bookmarks()' = 'builtin_remote_trunk_bookmarks(substring:"")'
'remote_trunk_bookmarks()' = 'builtin_remote_trunk_bookmarks()'
'builtin_upstream_trunks()' = 'remote_trunk_bookmarks(exact:"upstream")'
'upstream_trunks()' = 'builtin_upstream_trunks()'
'builtin_upstream_trunks(remote_pattern)' = 'upstream_trunks() & remote_trunk_bookmarks(remote_pattern)'
'upstream_trunks(remote_pattern)' = 'builtin_upstream_trunks(remote_pattern)'
'builtin_midstream_trunks()' = 'remote_trunk_bookmarks(exact:"origin")'
'midstream_trunks()' = 'builtin_midstream_trunks()'
'builtin_midstream_trunks(remote_pattern)' = 'midstream_trunks() & remote_trunk_bookmarks(remote_pattern)'
'midstream_trunks(remote_pattern)' = 'builtin_midstream_trunks(remote_pattern)'
'builtin_downstream_trunks()' = 'none()'
'downstream_trunks()' = 'builtin_downstream_trunks()'
'builtin_downstream_trunks(remote_pattern)' = 'downstream_trunks() & remote_trunk_bookmarks(remote_pattern)'
'downstream_trunks(remote_pattern)' = 'builtin_downstream_trunks(remote_pattern)'
'builtin_remote_trunks(remote_pattern)' = 'upstream_trunks(remote_pattern) | midstream_trunks(remote_pattern) | downstream_trunks(remote_pattern)'
'remote_trunks(remote_pattern)' = 'builtin_remote_trunks(remote_pattern)'
'builtin_remote_trunks()' = 'upstream_trunks() | midstream_trunks() | downstream_trunks()'
'remote_trunks()' = 'builtin_remote_trunks()'
'builtin_immutable_remote_trunks(remote_pattern)' = 'upstream_trunks(remote_pattern) | midstream_trunks(remote_pattern)'
'immutable_remote_trunks(remote_pattern)' = 'builtin_immutable_remote_trunks(remote_pattern)'
'builtin_immutable_remote_trunks()' = 'upstream_trunks() | midstream_trunks()'
'immutable_remote_trunks()' = 'builtin_immutable_remote_trunks()'
'builtin_mutable_remote_trunks(remote_pattern)' = 'remote_trunks(remote_pattern) ~ immutable_remote_trunks(remote_pattern)'
'mutable_remote_trunks(remote_pattern)' = 'builtin_mutable_remote_trunks(remote_pattern)'
'builtin_mutable_remote_trunks()' = 'remote_trunks() ~ immutable_remote_trunks()'
'mutable_remote_trunks()' = 'builtin_mutable_remote_trunks()'
'builtin_select_remote_trunk(remote_trunks)' = 'latest(remote_trunks)'
'select_remote_trunk(remote_trunks)' = 'builtin_select_remote_trunk(remote_trunks)'
'builtin_select_remote_trunk(remote_trunks, remote_pattern)' = 'select_remote_trunk(remote_trunks)'
'select_remote_trunk(remote_trunks, remote_pattern)' = 'builtin_select_remote_trunk(remote_trunks, remote_pattern)'
'builtin_upstream_trunk(remote_pattern)' = 'select_remote_trunk(upstream_trunks(remote_pattern), remote_pattern)'
'upstream_trunk(remote_pattern)' = 'builtin_upstream_trunk(remote_pattern)'
'builtin_upstream_trunk()' = 'select_remote_trunk(upstream_trunks())'
'upstream_trunk()' = 'builtin_upstream_trunk()'
'builtin_midstream_trunk(remote_pattern)' = 'select_remote_trunk(midstream_trunks(remote_pattern), remote_pattern)'
'midstream_trunk(remote_pattern)' = 'builtin_midstream_trunk(remote_pattern)'
'builtin_midstream_trunk()' = 'select_remote_trunk(midstream_trunks())'
'midstream_trunk()' = 'builtin_midstream_trunk()'
'builtin_downstream_trunk(remote_pattern)' = 'select_remote_trunk(downstream_trunks(remote_pattern), remote_pattern)'
'downstream_trunk(remote_pattern)' = 'builtin_downstream_trunk(remote_pattern)'
'builtin_downstream_trunk()' = 'select_remote_trunk(downstream_trunks())'
'downstream_trunk()' = 'builtin_downstream_trunk()'
'builtin_remote_trunk(remote_pattern)' = 'select_remote_trunk(remote_trunks(remote_pattern), remote_pattern)'
'remote_trunk(remote_pattern)' = 'builtin_remote_trunk(remote_pattern)'
'builtin_remote_trunk()' = 'select_remote_trunk(remote_trunks())'
'remote_trunk()' = 'builtin_remote_trunk()'
'builtin_immutable_remote_trunk(remote_pattern)' = 'select_remote_trunk(immutable_remote_trunks(remote_pattern), remote_pattern)'
'immutable_remote_trunk(remote_pattern)' = 'builtin_immutable_remote_trunk(remote_pattern)'
'builtin_immutable_remote_trunk()' = 'select_remote_trunk(immutable_remote_trunks())'
'immutable_remote_trunk()' = 'builtin_immutable_remote_trunk()'
'builtin_mutable_remote_trunk(remote_pattern)' = 'select_remote_trunk(mutable_remote_trunks(remote_pattern), remote_pattern)'
'mutable_remote_trunk(remote_pattern)' = 'builtin_mutable_remote_trunk(remote_pattern)'
'builtin_mutable_remote_trunk()' = 'select_remote_trunk(mutable_remote_trunks())'
'mutable_remote_trunk()' = 'builtin_mutable_remote_trunk()'
'builtin_trunks()' = 'remote_trunks()'
'trunks()' = 'builtin_trunks()'
'builtin_immutable_trunks()' = 'immutable_remote_trunks()'
'immutable_trunks()' = 'builtin_immutable_trunks()'
'builtin_mutable_trunks()' = 'trunks() ~ immutable_trunks()'
'mutable_trunks()' = 'builtin_mutable_trunks()'
'builtin_trunk()' = 'coalesce(present(remote_trunk()), root())'
'trunk()' = 'builtin_trunk()'
'builtin_immutable_heads()' = 'tags() | ((trunks() | untracked_remote_bookmarks()) ~ mutable_trunks())'
'builtin_log()' = 'present(@) | ancestors(immutable_heads().., 2) | upstream_trunks() | present(trunk())'
