[revset-aliases]
'builtin_remote_singular_immutable_trunk_bookmarks(remote_pattern)' = '''
remote_bookmarks(exact:"main", remote_pattern) |
remote_bookmarks(exact:"master", remote_pattern) |
remote_bookmarks(exact:"trunk", remote_pattern)
'''
'builtin_remote_singular_immutable_trunk(remote_pattern)' = 'latest(remote_singular_immutable_trunk_bookmarks(remote_pattern))'

'builtin_remote_plural_immutable_trunk_bookmarks(remote_pattern)' = '''
remote_bookmarks(glob:"trunk/**/*", remote_pattern) |
remote_bookmarks(glob:"trunks/**/*", remote_pattern)
'''
'builtin_remote_plural_immutable_trunks(remote_pattern)' = 'remote_plural_immutable_trunk_bookmarks(remote_pattern) ~ remote_singular_immutable_trunk_bookmarks(remote_pattern)'
'builtin_remote_immutable_trunks(remote_pattern)' = 'remote_singular_immutable_trunk(remote_pattern) | remote_plural_immutable_trunks(remote_pattern)'

'builtin_remote_plural_mutable_trunk_bookmarks(remote_pattern)' = '''
remote_bookmarks(exact:"seen", remote_pattern)
'''
'builtin_remote_mutable_trunks(remote_pattern)' = 'remote_plural_mutable_trunk_bookmarks(remote_pattern)'

'builtin_immutable_upstream_trunks()' = 'remote_immutable_trunks(exact:"upstream")'
'builtin_immutable_midstream_trunks()' = 'remote_immutable_trunks(exact:"origin")'
# the best i can do without the ability to map in revset expressions
'builtin_immutable_downstream_trunks()' = 'remote_plural_immutable_trunks(substring:"") ~ (present(immutable_upstream_trunks()) | present(immutable_midstream_trunks()))'

'builtin_mutable_upstream_trunks()' = 'remote_mutable_trunks(exact:"upstream")'
'builtin_mutable_midstream_trunks()' = 'remote_mutable_trunks(exact:"origin")'
'builtin_mutable_downstream_trunks()' = 'remote_mutable_trunks(substring:"") ~ (present(mutable_upstream_trunks()) | present(mutable_midstream_trunks()))'

'builtin_upstream_trunks()' = 'present(immutable_upstream_trunks()) | mutable_upstream_trunks()'
'builtin_midstream_trunks()' = 'present(immutable_midstream_trunks()) | mutable_midstream_trunks()'
'builtin_downstream_trunks()' = 'present(immutable_downstream_trunks()) | mutable_downstream_trunks()'

'builtin_immutable_trunks()' = 'present(immutable_upstream_trunks()) | present(immutable_midstream_trunks()) | present(immutable_downstream_trunks())'
'builtin_mutable_trunks()' = 'mutable_upstream_trunks() | mutable_midstream_trunks() | mutable_downstream_trunks()'
'builtin_trunks()' = 'immutable_trunks() | mutable_trunks()'

# 'builtin_immutable_heads()' = 'present(trunk()) | tags() | untracked_remote_bookmarks()'
'builtin_immutable_heads()' = 'immutable_trunks() | tags() | untracked_remote_bookmarks()'

'builtin_contextual_trunks()' = 'coalesce(present(immutable_upstream_trunks()) | present(immutable_midstream_trunks()), root())'

'trunk()' = 'latest(contextual_trunks())'

# 'builtin_log(domain)' = 'present(@) | ancestors(domain, 2) | present(trunk())'
'builtin_log(domain)' = 'present(@) | ancestors(domain, 2) | contextual_trunks()'
