# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, ... }:
{ config, lib, pkgs, ... }:

let
  nixos-hardware = inputs.nixos-hardware;
in
{
  # HP ZBook 14
  imports = [
    (nixos-hardware + "/common/cpu/intel") # Intel Core i7-4600U (Haswell)
    (nixos-hardware + "/common/gpu/amd/southern-islands") # TODO: verify
    (nixos-hardware + "/common/pc/laptop")
    (nixos-hardware + "/common/pc/laptop/ssd")
  ];
  config = {
    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "ehci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
      "sr_mod"
      "rtsx_pci_sdmmc"
    ];
    boot.initrd.kernelModules = [
      "kvm-intel"
    ];
    boot.kernelModules = [
    ];
    boot.extraModulePackages = [
    ];

    boot.loader.efi.canTouchEfiVariables = true;

    # Use the rEFInd boot loader.
    boot.loader.grub.enable = false;
    boot.loader.systemd-boot.enable = lib.mkForce false;
    system.boot.loader.id = "refind";
    boot.loader.systemd-boot.configurationLimit = 1;
    boot.loader.generationsDir.enable = true;
    boot.loader.generationsDir.copyKernels = true;

    hardware.bluetooth.enable = true;

    # Enables non-free firmware on devices not recognized by `nixos-generate-config`.
    hardware.enableRedistributableFirmware = lib.mkDefault true;

    hardware.ksm.enable = true;
    hardware.ksm.sleep = 1000;

    hardware.firmware = [ pkgs.wireless-regdb ];

    hardware.intelgpu.driver = "i915";

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

    nix.maxJobs = lib.mkDefault 3;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

    powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

    programs.firefox.preferences."browser.tabs.unloadOnLowMemory" = true;
  };
}
# vim: set sta et sw=2 ts=8:
