# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, ... }:
{ config, lib, ... }:

let
  nixos-hardware = inputs.nixos-hardware;
in
{
  # HP Z230 SFF
  imports = [
    (nixos-hardware + "/common/cpu/intel") # Intel Core i7-4790 (Haswell)
    (nixos-hardware + "/common/pc")
  ];
  config = {
    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "ehci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
      "sr_mod"
    ];
    boot.initrd.kernelModules = [
    ];
    boot.kernelModules = [
    ];
    boot.extraModulePackages = [
    ];

    boot.loader.efi.canTouchEfiVariables = true;

    # Enables non-free firmware on devices not recognized by `nixos-generate-config`.
    hardware.enableRedistributableFirmware = lib.mkDefault true;

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

    programs.firefox.preferences."browser.tabs.unloadOnLowMemory" = true;
  };
}
# vim: set sta et sw=2 ts=8:
