[[plugins]]
repo = '~/.local/share/dein/repos/github.com/Shougo/dein.vim'

# normal plugins

[[plugins]]
repo = 'ciaranm/securemodelines'
on_event = 'BufRead'

[[plugins]]
repo = 'equalsraf/neovim-gui-shim'

[[plugins]]
repo = 'hecal3/vim-leader-guide'
lazy = 1
hook_post_source = '''
call leaderGuide#register_prefix_descriptions("\<LocalLeader>", "g:llmap")
call leaderGuide#register_prefix_descriptions('', "g:topdict")
function! s:my_displayfunc()
    let g:leaderGuide#displayname = substitute(g:leaderGuide#displayname, '^<SID>(\(.*\))$', '\1', '')
    let g:leaderGuide#displayname = substitute(g:leaderGuide#displayname, '^\w\{-1,}-', '', '')
endfunction
let g:leaderGuide_displayfunc = [function('s:my_displayfunc')]
'''
on_cmd = ['LeaderGuide', 'LeaderGuideVisual', 'LeaderGuideD', 'LeaderGuideVisualD']
[plugin.on_map]
nx = ['<Plug>leaderguide-global', '<Plug>leaderguide-buffer']

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'junegunn/goyo.vim'
lazy = 1
on_cmd = 'Goyo'

# [[plugins]]
# repo = 'kana/vim-repeat'

[[plugins]]
repo = 'kana/vim-smartchr'
lazy = 1
on_event = 'InsertCharPre'
hook_source = '''
augroup MyAutoCmd
    autocmd FileType c,cpp inoremap <buffer> <expr> .
        \ smartchr#loop('.', '->', '...')
augroup END
'''

[[plugins]]
repo = 'katono/rogue.vim'
lazy = 1
on_cmd = ['Rogue', 'RogueScores', 'RogueResume']

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'nixprime/cpsm'
build = "dash -c 'PY3=ON ./install.sh'"

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
let $RUST_SRC_PATH = expand('~/.multirust/toolchains/'
    \ .'stable-x86_64-unknown-linux-gnu/'
    \ .'lib/rustlib/src/rust/src/')
'''

[[plugins]]
repo = 'rhysd/rust-doc.vim'
lazy = 1
on_ft = 'rust'
on_cmd = ['RustDoc', 'RustDocFuzzy', 'RustDocModule']

[[plugins]]
repo = 'rust-lang/rust.vim'
lazy = 1
on_ft = 'rust'
on_cmd = 'RustPlay'

[[plugins]]
repo = 'sgur/vim-editorconfig'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
lazy = 1
hook_post_source = '''
augroup deniteresize
    autocmd!
    autocmd VimResized,VimEnter * call denite#custom#option('default,
        \'winheight', winheight(0) / 2)
augroup end
call denite#custom#option('default', {
    \ 'prompt': '>'
    \ })
call denite#custom#var('file_rec', 'command',
    \ ['rg', '--files', ':directory'])
call denite#custom#source('file_rec', 'matchers', ['matcher_cpsm'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts',
    \ ['--hidden', '--vimgrep', '--no-heading', '-S'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
'''
on_cmd = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord', 'DeniteProjectDir']

[[plugins]]
repo = 'Shougo/deol.nvim'
lazy = 1
on_cmd = ['Deol', 'DeolCd', 'DeolEdit']

[[plugins]]
repo = 'Shougo/junkfile.vim'
lazy = 1
on_cmd = 'JunkfileOpen'
on_func = ['junkfile#open', 'junkfile#open_immediately', 'junkfile#init', 'junkfile#_open']
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
lazy = 1
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = '''
  imap <silent> <C-k> <Plug>(neosnippet_jump_or_expand)
  smap <silent> <C-k> <Plug>(neosnippet_jump_or_expand)
  xmap <silent> <C-k> <Plug>(neosnippet_expand_target)
  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vinarise.vim'
lazy = 1
on_cmd = 'Vinarise'

[[plugins]]
repo = 'tommcdo/vim-lion'
lazy = 1
[plugins.on_map]
n = ['<Plug>LionRepeat', '<Plug>LionRight', '<Plug>LionLeft']
x = ['<Plug>VLionRight', '<Plug>VLionLeft']

[[plugins]]
repo = 'tpope/vim-characterize'
lazy = 1
[plugins.on_map]
n = 'ga'

[[plugins]]
repo = 'tpope/vim-commentary'
depends = 'vim-repeat'
lazy = 1
on_cmd = 'Commentary'
[plugins.on_map]
nxo = ['gc']

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-repeat'
lazy = 1
[plugins.on_map]
nx = '.'

[[plugins]]
repo = 'tpope/vim-surround'
depends = 'vim-repeat'
lazy = 1
[plugins.on_map]
n = ['cs', 'ds', 'ys']
x = ['S']

[[plugins]]
repo = 'tweekmonster/startuptime.vim'
lazy = 1
on_cmd = 'StartupTime'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'wellle/targets.vim'

# theme

[[plugins]]
repo = 'guns/xterm-color-table.vim'
lazy = 1
on_cmd = 'XtermColorTable'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

# syntax

[[plugins]]
repo = 'cespare/vim-toml'
