[[plugins]]
repo = 'Shougo/deoplete.nvim'
lazy = 1
on_event = 'InsertEnter'
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.config/nvim/deoplete.rc.vim
'''

# completions

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
lazy = 1
on_ft = 'java'
on_func = 'javacomplete#logger#Enable'
hook_source = '''
autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'fszymanski/deoplete-emoji'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neco-vim'
lazy = 1
on_ft = 'vim'

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
lazy = 1
on_ft = ['c', 'cpp']
# disable fancy Obj-C stuff
hook_source = '''
autocmd FileType c,cpp let b:clang2_orig_maps = {}
'''

[[plugins]]
repo = 'zchee/deoplete-zsh'
lazy = 1
on_ft = 'zsh'
